### ISSUE TITLE
Support for Avatto WT200 electric floor heating thermostat

### ISSUE THREAD

**Issue by andreas-bulling** [klausahrenberg/WThermostatBeca#309]
It would be fantastic if there was support for the [Avatto WT200 electric floor heating thermostat](https://de.aliexpress.com/item/1005005104774576.html?spm=a2g0o.home.0.0.22e712e2GB7krD&mp=1&gatewayAdapt=glo2deu) - this device is the only one I could find that fits into the the standard 55mm frames.

**Comment by NonPIayerCharacter** [comment]
I have Avatto WT100 thermostat (ordered without wifi, then soldered esp12f). There is no support for it here, so i used esphome. Tuya datapoints should be similar, and if not, then it should be easily adaptable (esphome dumps most available datapoints in log).
```
esphome:
  name: wt-100
  friendly_name: WT-100

esp8266:
  board: esp12e

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

api:
  encryption:
    key: "---"

ota:
  password: "---"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Wt-100 Fallback Hotspot"
    password: "---"

status_led:
  pin: GPIO2

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: UTC-00:00 # Adjust for yourself, for example if your timezone in hass is +2, then use -2 here.

tuya:
  id: tuyamcu
  time_id: homeassistant_time

climate:
  - platform: tuya
    name: "Floor"
    active_state_datapoint: 5
    active_state_heating_value: 1
    switch_datapoint: 1
    target_temperature_datapoint: 2
    target_temperature_multiplier: 0.1
    current_temperature_datapoint: 3
    current_temperature_multiplier: 0.1
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1
      min_temperature: 5 °C
      max_temperature: 60 °C

switch:
  - platform: restart
    name: Restart
  - platform: "tuya"
    name: "Child lock"
    switch_datapoint: 9
  - platform: "tuya"
    name: "Anti-freeze"
    switch_datapoint: 103
  - platform: "tuya"
    name: "Sound"
    switch_datapoint: 109

select:
  - platform: "tuya"
    tuya_id: tuyamcu
    name: "Sensor selection"
    enum_datapoint: 110
    options:
      0: Internal
      1: Floor
      2: Both
  - platform: "tuya"
    tuya_id: tuyamcu
    name: "Backlight"
    enum_datapoint: 106
    options:
      0: "Off"
      1: Micro-light
      2: Medium brightness
      3: Backlight highlight

number:
  - platform: "tuya"
    name: "Temperature compensation"
    number_datapoint: 19
    min_value: -9.9
    max_value: 9.9
    step: 0.1
    multiply: 10
  - platform: "tuya"
    name: "Switching differential"
    number_datapoint: 101
    min_value: 0.5
    max_value: 10
    step: 0.5
    multiply: 10

captive_portal:
    
```
