### ISSUE TITLE
Homeassistant does not see the thermostat via MQTT.

### ISSUE THREAD

**Issue by mistikdonbass** [klausahrenberg/WThermostatBeca#310]
Good afternoon  I can't pair the thermostat with homeassistant via MQTT.  My thermostat and settings in screenshots.
 What did I miss, what did I do wrong?
![IMG_20231016_190439](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/5f1d4516-cc75-429d-807f-0fc9f4a77601)
![IMG_20231016_190421](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/c0b8117c-6ebd-4e1b-8d72-cffe6db5469a)
![IMG_20231016_190421](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/2af57b8d-0ce4-4daf-b785-3c00d7f8a48e)
![Screenshot_20231016_190321](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/34da6848-e62b-4fea-8da8-960a147a90cc)
![Screenshot_20231016_190259](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/5a5e29f7-61a3-45fb-9ad0-4095bf233fd0)
![Screenshot_20231016_190321](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/7b77b835-adf1-4740-9eea-65afb5a2672c)
![Screenshot_20231016_190259](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/9cbe63ad-113a-427d-adda-caa5cf732ec9)
I also tried installing another firmware from this topic: https://github.com/fashberg/WThermostatBeca/tree/master 
with this firmware it connects to homeassistant, but does not transmit information about temperatures (set and actual).

**Comment by k-zakhariy** [comment]
@mistikdonbass what's your configuration on HA side ?

**Comment by mistikdonbass** [comment]
> @mistikdonbass what's your configuration on HA side ?

Thanks for the quick response.

Judging by MQTT Explorer, it connects to HA and transfers data. But it does not appear on devices.
![nqtt](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/38921475-aa9d-4a10-a18a-10775d860655)
![mqtt2](https://github.com/klausahrenberg/WThermostatBeca/assets/135098430/742fdec9-88f7-45f8-8976-b0a252e939cf)

**Comment by Arquiteto** [comment]
There is no auto discovery on this firmware so you must configure your MQTT climate entity manually. Here is some example code, but you need to adjust to your topics.

```
mqtt:
  climate:
      - name: Łazienka sterownik podłogowy
        temperature_command_topic: "termostat_lazienka/thermostat/set/targetTemperature"
        temperature_state_topic: "termostat_lazienka/thermostat/properties"
        temperature_state_template: "{{ value_json['targetTemperature'] | round(1) }}"
        current_temperature_topic: "termostat_lazienka/thermostat/properties"
        current_temperature_template: "{{value_json['temperature'] | round(1) }}"
        mode_state_topic: "termostat_lazienka/thermostat/properties"
        mode_state_template: >
          {% if value_json.deviceOn != true %}
          off
          {% elif value_json.schedulesMode == 'auto' %}
          auto
          {% else %}
          heat
          {% endif %}
        modes:
          - "heat"
          - "auto"
          - "off"
        min_temp: 10
        max_temp: 30
        temp_step: 0.5
        precision: 0.5
        retain: true
```

**Comment by mistikdonbass** [comment]
> There is no auto discovery on this firmware so you must configure your MQTT climate entity manually. Here is some example code, but you need to adjust to your topics.

Thanks a lot.
I already understood this and used a more complex config.
Works too.

```
mqtt: #Настройка термостата для бойлера
  climate:
    - name: Thermostat
      unique_id: termostat
      device:
        configuration_url: http://192.168.1.166/config
        manufacturer: Tuya
        model: ME81AH
        connections: [["mac", "E8: DB: 84:D1: EF:33"]]
      temperature_command_topic: thermostat/thermostat/set
      temperature_command_template: >
        {{ {'targetTemperature':value} | to_json }}
      temperature_state_topic: thermostat/thermostat/properties
      temperature_state_template: >
        {% if value_json is defined and value_json['targetTemperature'] is defined %}
          {{ value_json['targetTemperature'] }}
        {% endif %}  
      current_temperature_topic: thermostat/thermostat/properties
      current_temperature_template: >
        {% if value_json is defined and value_json['temperature'] is defined %}
          {{ value_json['temperature'] }}
        {% endif %}  
      mode_state_topic: thermostat/thermostat/properties
      mode_state_template: >
        {% if value_json is defined and value_json['deviceOn'] is defined %}
          {% set deviceOn = value_json['deviceOn'] %}
        {% else %}
          {% set deviceOn = false %}
        {% endif %}
  
        {% if value_json is defined and value_json['schedulesMode'] is defined %}
          {% set schedulesMode = value_json['schedulesMode'] %}
        {% else %}
          {% set schedulesMode = 'off' %}
        {% endif %}
  
        {% if deviceOn == true %}
          {% if schedulesMode == 'auto' %}
            auto
          {% else %}
            heat
          {% endif %}
        {% else %}
          off
        {% endif %}
      action_topic: thermostat/thermostat/properties
      action_template: >
        {% if value_json is defined and value_json['systemMode'] is defined %}
          {% set deviceOn = value_json['deviceOn'] %}
        {% else %}
          {% set deviceOn = false %}
        {% endif %}
        
        {% if value_json is defined and value_json['systemMode'] is defined %}
          {% set systemMode = value_json['systemMode'] %}
        {% else %}
          {% set systemMode = 'off' %}
        {% endif %}
        
        {% if deviceOn == true %}
          {% if systemMode == 'cool' %}
            idle
          {% elif systemMode == 'heat' %}
            heating
          {% endif %}
        {% else %}
          off
        {% endif %}
      mode_command_topic: thermostat/thermostat/set
      mode_command_template: >
        {% if value == 'auto' %}
          {{ {'deviceOn':true,'schedulesMode':'auto'} | to_json }}
        {% endif %}
  
        {% if value == 'heat' %}
          {{ {'deviceOn':true,'schedulesMode':'off'} | to_json }}
        {% endif %}
  
        {% if value == 'off' %}
          {{ {'deviceOn':false,'schedulesMode':'off'} | to_json }}
        {% endif %}
      modes:
        - "auto"
        - "heat"
        - "off"
      temperature_unit: C
      temp_step: 1
      min_temp: 5
      max_temp: 85
      initial: 20
      retain: true
      qos: 0

```

Your proposed configuration makes more sense to me. But I don’t understand why the thermostat doesn’t turn off.
If you click on turn off.

**Comment by Arquiteto** [comment]
The template you posted works better. I had a very basic one for a different thermostat which was only to serve as an example. This works better (I have installed ME81H just today so I was able to check)

**Comment by yhunter-ru** [comment]
My HA template for BHT-002:

```
mqtt:
  climate:
    - name: Thermostat
      unique_id: termostat
      device:
        configuration_url: http://192.168.1.187/config
        manufacturer: Moes
        model: BHT-002
        connections: [["mac", "98:F4:AB:BF:78:D1"]]
        
      current_temperature_topic: thermostat_12548305/thermostat/properties/temperature
      temperature_command_topic: thermostat_12548305/thermostat/set/targetTemperature
      temperature_state_topic: thermostat_12548305/thermostat/properties/targetTemperature
      mode_state_topic: thermostat_12548305/thermostat/properties/schedulesMode
      mode_state_template: >
        {% if value == 'auto' %}
          auto
        {% else %}
          heat
        {% endif %}

      mode_command_topic: thermostat_12548305/thermostat/set/schedulesMode
      mode_command_template: >
        {% if value == 'auto' %}
          auto

        {% else %}
          off
        {% endif %}

      modes:
        - "auto"
        - "heat"
      temperature_unit: C
      temp_step: .5
      min_temp: 15
      max_temp: 35
      initial: 25
      retain: true
      qos: 0
```
